import Head from "next/head";
// import Image from "next/image";
import Experience from "../components/tables";
import Hero from "../components/hero";
import Contacts from "../components/contacts";

const titleName = "Portfolio Filipe Martins";

export default function Home() {
  return (
    <div className="antialiased">
      <Head>
        <title>{titleName}</title>
        <meta
          name="description"
          content="Portfolio generated by create next app and made by Filipe Martins"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-sans">
        <div>
          {/* fazer uma lista com about minimalista, fazer flex col em lg:viewport */}
          <section>
            <Hero />
          </section>
          <section>
            <Contacts />
          </section>
          <section>
            <Experience />
          </section>
        </div>

        {/* content here */}
      </main>

      <footer>{/* social links here */}</footer>
    </div>
  );
}
