import Head from "next/head";
// import Image from "next/image";
import Experience from "../components/tables";
import About from "../components/about";

const titleName = "Portfolio Filipe Martins";

export default function Home() {
  return (
    <div>
      <Head>
        <title>{titleName}</title>
        <meta
          name="description"
          content="Portfolio generated by create next app and made by Filipe Martins"
        />
        <meta charSet="utf-8"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="space-y-6">
          {/* avatar */}

          <section className="mt-4" id="layout">
            <About />
          </section>
          <section>
            <Experience />
          </section>
        </div>

        {/* content here */}
      </main>

      <footer>{/* social links here */}</footer>
    </div>
  );
}
